
spring:
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8   #??????????,? 0 ?????
        max-idle: 8     #??????????,? 0 ?????
        max-wait: -1ms  #??????????????????????????-1??????
        min-idle: 0     #??????????,? 0 ?????
      shutdown-timeout: 100ms
    password: root
    port: 6379
jeecg :
  redisson:
    address: 127.0.0.1:6379
    type: STANDALONE
    password: root
    enabled: true
server:
  port: 9889
